version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: shipment_tracker_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: shipment_user
      POSTGRES_PASSWORD: shipment_pass
      POSTGRES_DB: shipment_tracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
